name: Referral
version: 2.2.3
api-version: 1.20
author: Teenaapje
main: Me.Teenaapje.Referral.ReferralCore
description: Referral
folia-supported: true
softdepend: [PlaceholderAPI]
commands:
   Ref:
      description: /Ref to get more options